version: '3.8'

services:
  # PostgreSQL データベース
  postgres:
    image: postgres:15-alpine
    container_name: dandori-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: dandori_scheduler
      POSTGRES_USER: dandori_user
      POSTGRES_PASSWORD: dandori_pass_2025
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dandori_user -d dandori_scheduler"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis (将来のセッション管理・キャッシュ用)
  redis:
    image: redis:7-alpine
    container_name: dandori-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data: